### ISSUE TITLE
How to decompress?

### ISSUE THREAD

**Issue by dmikushin** [vcskaushik/LLMzip#1]
Hi, thank you for this project!

After compression is finished, how to decompress? Could you please add an example command to perform decompression?

**Comment by vcskaushik** [comment]
Hi @dmikushin,
Here is the command for running it. This will both compress and decompress and verify if the decompressed text matches the original. 

```
torchrun --nproc_per_node 1 LLMzip_run.py --ckpt_dir $TARGET_FOLDER/model_size --tokenizer_path $TARGET_FOLDER/tokenizer.model --win_len 511 --text_file $TEXT_FILE --compression_folder $COMPRESSION_FOLDER 
```

Do let us know if you run into any other issues. 
Thanks
