### ISSUE TITLE
Use for non-text data?

### ISSUE THREAD

**Issue by dmikushin** [vcskaushik/LLMzip#2]
Dear authors,

To what extent this work could be potentially applied to non-textual data? Have you done any experiments?

Thank you!

**Comment by vcskaushik** [comment]
Sorry for the late reply. But the idea would work for other data as well.

We haven't done any experiments, but this paper from Google shows that even an LLM trained on text can even compress images "well enough".

https://arxiv.org/abs/2309.10668
